{{ Html::script('https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js')}}
{{ Html::script('admin/assets/nicescroll/jquery.nicescroll.min.js') }}
{{ Html::script('admin/assets/bootstrap/js/bootstrap.min.js') }}
{{ Html::script('admin/assets/charts/table-to-chart.js') }}
{{ Html::script('admin/assets/fullcalendar/fullcalendar.min.js') }}
{{ Html::script('admin/assets/fullcalendar/gcal.js') }}
{{ Html::script('admin/assets/sidebar/min-height.js') }}
{{ Html::script('admin/assets/datatables/jquery.dataTables.min.js') }}
{{ Html::script('admin/assets/jquery-ui/jquery-ui-1.10.3.custom.min.js') }}
{{ Html::script('admin/assets/morrischarts/raphael.js') }}
{{ Html::script('admin/assets/morrischarts/morris.js') }}
{{ Html::script('admin/assets/icheck/icheck.js') }}
{{ Html::script('admin/assets/jquery-countto/jquery.count-to.js') }}
{{ Html::script('admin/assets/flotcharts/flotcharts-common.js') }}
{{ Html::script('admin/assets/flotcharts/jquery.flot.min.js') }}
{{ Html::script('admin/assets/flotcharts/jquery.flot.resize.min.js') }}
{{ Html::script('admin/assets/flotcharts/jquery.flot.canvas.min.js') }}
{{ Html::script('admin/assets/flotcharts/jquery.flot.image.min.js') }}
{{ Html::script('admin/assets/flotcharts/jquery.flot.categories.min.js') }}
{{ Html::script('admin/assets/flotcharts/jquery.flot.crosshair.min.js') }}
{{ Html::script('admin/assets/flotcharts/jquery.flot.errorbars.min.js') }}
{{ Html::script('admin/assets/flotcharts/jquery.flot.fillbetween.min.js') }}
{{ Html::script('admin/assets/flotcharts/jquery.flot.navigate.min.js') }}
{{ Html::script('admin/assets/flotcharts/jquery.flot.pie.min.js') }}
{{ Html::script('admin/assets/flotcharts/jquery.flot.selection.min.js') }}
{{ Html::script('admin/assets/flotcharts/jquery.flot.stack.min.js') }}
{{ Html::script('admin/assets/flotcharts/jquery.flot.symbol.min.js') }}
{{ Html::script('admin/assets/flotcharts/jquery.flot.threshold.min.js') }}
{{ Html::script('admin/assets/flotcharts/jquery.colorhelpers.min.js') }}
{{ Html::script('admin/assets/flotcharts/jquery.flot.time.min.js') }}
{{ Html::script('admin/_demo/icheck/icheck.js') }}
{{ Html::script('admin/_demo/charts/dashboard.js') }}
{{ Html::script('admin/_demo/all-pages.js') }}
{{ Html::script('admin/_demo/page-index.js') }}
{{ Html::script('admin/_demo/introjs/intro.min.js') }}
{{ Html::script('admin/js/developer.js') }}
{{ Html::script('admin/js/year-select.js') }}
{{ Html::script('https://cdnjs.cloudflare.com/ajax/libs/bxslider/4.2.12/jquery.bxslider.js') }}
{{ Html::script('https://cdnjs.cloudflare.com/ajax/libs/bxslider/4.2.12/jquery.bxslider.min.js') }}
{{ Html::script('//cdn.ckeditor.com/4.4.3/standard/ckeditor.js') }}
